# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47494df4def780ad284a309b1dd6f47c8a998fa38870d2e03a87d581f33ff3c6191f81104f645d7f84913320012acca6a28571ae2e73226a949da1a4ab47fca8

test:
  secret_key_base: 9512b2e2711ece34c68a1335b4d52248317f3548b7f66f5655ae83d355397d2a3611a0e290eab55b720e4b4236ba03efb09054dffaf42ac9bfbe3d2c3c640f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
